# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: "Yan LEI"
title_en: "Yan LEI"
title_cn: "（雷晏）"
description: THis is Yan's website.
baseurl: ""
url: "https://ly671122.github.io"

# theme: bay_jekyll_theme

header:
  pages:
    - name: Home
      slug: /
    - name: Curriculum Vitae
      slug: /cv
    - name: Research
      slug: /research

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: yourmail@domain.com
#  follow:
#    - type: linkedin
#      name: LinkedIn
#      link: http://linkedin.com/in/YourLinkedInUsername
#    - type: github
#      name: GitHub
#      link: http://github.com/YourGitHubUsername

# Build settings
markdown: kramdown
sass:
    style: compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
